apiVersion: apps/v1
kind: StatefulSet
metadata:
  # creationTimestamp: 2018-10-01T08:54:46Z
  # generation: 1
  labels:
    app: consul
    # chart: consul-0.1.0
    # heritage: Tiller
    release: test-20181011
  name: test-20181011-consul-server
  namespace: nalej
  # resourceVersion: "193042"
  # selfLink: /apis/apps/v1/namespaces/zone-a/statefulsets/honking-chimp-consul-server
  # uid: a5825b09-c557-11e8-abb7-080027d62bfd
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: consul
      # chart: consul-0.1.0
      component: server
      hasDNS: "true"
      release: test-20181011
  serviceName: test-20181011-consul-server
  template:
    metadata:
      # annotations:
      #   consul.hashicorp.com/connect-inject: "false"
      # creationTimestamp: null
      labels:
        app: consul
        # chart: consul-0.1.0
        component: server
        hasDNS: "true"
        release: test-20181011
    spec:
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          CONSUL_FULLNAME="test-20181011-consul"

          exec /bin/consul agent \
            -advertise="${POD_IP}" \
            -bind=0.0.0.0 \
            -bootstrap-expect=3 \
            -client=0.0.0.0 \
            -config-dir=/consul/config \
            -datacenter=dc1 \
            -data-dir=/consul/data \
            -domain=consul \
            -hcl="connect { enabled = true }" \
            -ui \
            -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
            -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
            -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
            -server
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: consul:1.2.3
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
        name: consul
        ports:
        - containerPort: 8500
          name: http
          protocol: TCP
        - containerPort: 8301
          name: serflan
          protocol: TCP
        - containerPort: 8302
          name: serfwan
          protocol: TCP
        - containerPort: 8300
          name: server
          protocol: TCP
        - containerPort: 8600
          name: dns-tcp
          protocol: TCP
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - |
              curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
              grep -E '".+"'
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /consul/data
          name: data
        - mountPath: /consul/config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          name: test-20181011-consul-server-config
        name: config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    status:
      phase: Pending
# status:
#   collisionCount: 0
#   currentReplicas: 3
#   currentRevision: honking-chimp-consul-server-768d7769f4
#   observedGeneration: 1
#   readyReplicas: 3
#   replicas: 3
#   updateRevision: honking-chimp-consul-server-768d7769f4
