apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # annotations:
  #   control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"efdea547-c547-11e8-bd6e-080027d62bfd","leaseDurationSeconds":15,"acquireTime":"2018-10-01T08:54:46Z","renewTime":"2018-10-01T08:54:48Z","leaderTransitions":0}'
  #   pv.kubernetes.io/bind-completed: "yes"
  #   pv.kubernetes.io/bound-by-controller: "yes"
  #   volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  # creationTimestamp: 2018-10-01T08:54:46Z
  labels:
    app: consul
    # chart: consul-0.1.0
    component: server
    hasDNS: "true"
    release: dns-test
  name: data-dns-test-consul-server-1
  namespace: nalej
  # resourceVersion: "85366"
  # selfLink: /api/v1/namespaces/zone-a/persistentvolumeclaims/data-dns-test-consul-server-0
  # uid: a58795f4-c557-11e8-abb7-080027d62bfd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: pvc-dns-test-consul-server-1
# status:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 10Gi
#   phase: Bound
