apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
    release: dns-test
  name: dns-test-consul-ui
  namespace: nalej
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul
    component: server
    release: dns-test
  sessionAffinity: None
  type: ClusterIP
