apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  labels:
    app: consul
    release: dns-test
  name: dns-test-consul-server
  namespace: nalej
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: consul
      component: server
      release: dns-test
