apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul
    component: server
    hasDNS: "true"
    release: dns-server
  name: data-dns-server-2
  namespace: __NPH_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pvc-dns-server-2
