apiVersion: v1
data:
  extra-from-values.json: '{}'
kind: ConfigMap
metadata:
  labels:
    app: consul
    release: dns-server
    cluster: management
    component: dns-server
  name: dns-server-config
  namespace: nalej
