apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
    release: dns-server
    cluster: management
    component: dns-server
  name: dns-server-ui
  namespace: __NPH_NAMESPACE
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8500
  selector:
    app: consul
    component: dns-server
    release: dns-server
  sessionAffinity: None
  type: ClusterIP
