apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
    release: dns-server
    cluster: management
    component: dns-server
  name: dns-nodeport
  namespace: nalej
spec:
  type: NodePort
  selector:
    app: consul
    component: dns-server
    release: dns-server
  ports:
  - port: 8600
    targetPort: 8600
    nodePort: 30600
    protocol: TCP
    name: dns-tcp
  - port: 8600
    targetPort: 8600
    nodePort: 30600
    protocol: UDP
    name: dns-udp
  # HTTP API
  - port: 8500
    targetPort: 8500
    nodePort: 30500
    protocol: TCP
    name: consul-gui
