apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
    release: dns-server
    cluster: management
    component: dns-server
  name: dns-server-consul-dns
  namespace: nalej
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: consul
    hasDNS: "true"
    release: dns-server
  sessionAffinity: None
  type: LoadBalancer
